services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8879:80
        depends_on:
            - app
        container_name: project_insta_nginx

    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        container_name: project_insta_app

    db:
        image: mysql:8.0
        restart: always
        ports:
            - 8079:3306
        environment:
            MYSQL_DATABASE: insta_rest_api_db
            MYSQL_ROOT_PASSWORD: root
        container_name: project_insta_db
